import ToastProvider from '@/src/components/toastProvider/ToastProvider';
import './globals.css';
import { Inter } from 'next/font/google';
import Footer from '@/src/layouts/footer/Footer';
import Header from '@/src/layouts/header/Header';
import ReduxProviders from '@/src/redux/provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  // if (typeof window === 'undefined') {
  //   return null;
  // }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProviders>
          <Header />
          <ToastProvider>{children}</ToastProvider>
          <Footer />
        </ReduxProviders>
      </body>
    </html>
  );
}
